feat: Add ZohoCRM samples
amp-labs/samples pull request #7
Opened 2024-12-30 08:09 UTC by Jkarage

2025-01-06 23:09 UTC, laurenzlong requested changes
@Jkarage does lower case versions of object and field names work? (e.g. `deals` and `account_name`), we normally use lower case in amp.yaml files. If the capitalized versions are required, can you please modify the connector to work with lower case names?

2025-01-07 09:01 UTC, Jkarage commented
@laurenzlong The lowercase of objects works fine. The field names requires an update on the connector. Working on a PR to update it.

2025-01-07 12:04 UTC, Jkarage commented
@laurenzlong Am also updating this(Metadata Connector) to return all lowercase. Currently it's in this state. So it's all in one format.
<img width="1183" alt="Screenshot 2025-01-07 at 15 00 47" src="https://github.com/user-attachments/assets/15b2481b-3f02-435e-be61-4a2563f32632" />

2025-01-15 22:37 UTC, laurenzlong approved these changes

2025-01-15 22:37 UTC, merged